@extends('layouts.master_march')

@section('title')
    ESG Prakrit
@endsection




@section('content')



<!-- ESG PRAKRIT -->
<section class="esg-prakrit mt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="esg-prakrit-info">
                    <h2>ESG PRAKRIT - A Comprehensive Dashboard</h2>
                    <p>ESG PRAKRIT is a dynamic dashboard that supports Banks & Corporates in their Environmental, Social, and Governance (ESG) journey. Our comprehensive suite of services includes tools like the Financed Emissions GHG Calculator, ESG Strategy, ESG Risk, Climate Risk, Environmental Impact, Social Impact, Sustainability Reporting, Governance Matrix, Regulatory Reports, ESG Assurance, United Nations Sustainable Development Goals (UN SDG) Mapping, Net-Zero Plan, Carbon Credits, Carbon Footprint, and Carbon Sequestration. In the future, we will integrate ESG Scoring and Rating Services, enabling banks, corporates, and financial institutions to assess their sustainability performance.</p>

                    <p style="text-align:justify">We aim to be a leading provider of ESG intelligence solutions in India, supporting the country's transition to a low-carbon economy and contributing to global climate goals. The tool aligns with the National Guidelines on Responsible Business Conduct (NGRBC’s), complies with the regulations set forth by the Reserve Bank of India (RBI) and the Securities & Exchange Board of India (SEBI). We will empower organizations to integrate responsible and sustainable practices into their operations, supply chain & navigate the complex ESG landscape. </p>

                    <p style="text-align:justify"> The platform's mission is to empower financial & other institutions to drive sustainable decision-making and manage their environmental impact. ESG PRAKRIT, rooted in the philosophy of “Sabka Saath, Sabka Vikas”, promotes socio-economic transformation and growth by integrating business practices. As India announced its commitment to achieve net-zero emissions by 2070 during the 26th session of the United Nations Framework Convention on Climate Change (COP 26) in November 2021. To support these ambitious targets, the ESG PRAKRIT a pioneering "Made in India" tool will contribute significantly to achieve India’s climate goals & enhancing its resilience against climate change impacts. The tool empowers organizations to integrate sustainability into their core operations, foster accountability, transparency & long-term value creation, moreover it quantifies their contribution towards Sustainable Development Goals. </p>

                    <p style="text-align:justify"> The tool is relevant as India is in a bright spot in the world economy. There is a visible shift in the world economic order. Over the past few years, India has witnessed a consistent GDP growth of 6-7% as against world GDP growth of 2-3%. India is now amongst the top 5 economies of the world.</p>

                    <p style="text-align:justify">Climate Risk is a major threat to world economic growth. As per a study by Carbon Brief, a 1.5 – 2.0 Degree Celsius temperature increase will erode 8% - 13% of global GDP by 2100. In view of the above, the financial sector must play a pivotal role in driving the ESG agenda for the economy. The flow of funds towards ESG and Sustainability is critical for India to lead the world economic growth. It is increasingly becoming important to measure and track the greenhouse gas (GHG) emissions of corporates. Accurately measuring and consistently monitoring greenhouse gas (GHG) emissions is essential for evaluating the overall carbon footprint generated by corporations-standalone, investment portfolios held by banks or financial institutions, and the entire banking sector.  </p>

                    <p style="text-align:justify">Additionally, the tool will assess the financed emissions by taking pre-emptive measures, as it is aligned with global benchmarks like Partnership for Carbon Accounting Financials (PCAF), Task Force on Climate-related Financial Disclosures (TCFD), Greenhouse Gas Protocol (GHG Protocol) and in line with the Reserve Bank of India (RBI’s) climate risk policies. The tool can further help develop Small and Medium Enterprises (SME)- specific guidelines as well as create an internal rating assessment model.  </p>
                    
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ESG PRAKRIT end -->




@endsection